// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_registration.proto

package grpctest

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type RegisterUserRequest struct {
	Email                string                                `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string                                `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                                `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Birthday             *timestamp.Timestamp                  `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	PhoneNumber          string                                `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	SecurityQuestion     *RegisterUserRequest_SecurityQuestion `protobuf:"bytes,6,opt,name=security_question,json=securityQuestion,proto3" json:"security_question,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02355805e6aa75f, []int{0}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *RegisterUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *RegisterUserRequest) GetSecurityQuestion() *RegisterUserRequest_SecurityQuestion {
	if m != nil {
		return m.SecurityQuestion
	}
	return nil
}

type RegisterUserRequest_SecurityQuestion struct {
	Question             string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest_SecurityQuestion) Reset()         { *m = RegisterUserRequest_SecurityQuestion{} }
func (m *RegisterUserRequest_SecurityQuestion) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest_SecurityQuestion) ProtoMessage()    {}
func (*RegisterUserRequest_SecurityQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02355805e6aa75f, []int{0, 0}
}

func (m *RegisterUserRequest_SecurityQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest_SecurityQuestion.Unmarshal(m, b)
}
func (m *RegisterUserRequest_SecurityQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest_SecurityQuestion.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest_SecurityQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest_SecurityQuestion.Merge(m, src)
}
func (m *RegisterUserRequest_SecurityQuestion) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest_SecurityQuestion.Size(m)
}
func (m *RegisterUserRequest_SecurityQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest_SecurityQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest_SecurityQuestion proto.InternalMessageInfo

func (m *RegisterUserRequest_SecurityQuestion) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *RegisterUserRequest_SecurityQuestion) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

// The response message containing the greetings
type RegisterUserReply struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserReply) Reset()         { *m = RegisterUserReply{} }
func (m *RegisterUserReply) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReply) ProtoMessage()    {}
func (*RegisterUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02355805e6aa75f, []int{1}
}

func (m *RegisterUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReply.Unmarshal(m, b)
}
func (m *RegisterUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReply.Marshal(b, m, deterministic)
}
func (m *RegisterUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReply.Merge(m, src)
}
func (m *RegisterUserReply) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReply.Size(m)
}
func (m *RegisterUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReply proto.InternalMessageInfo

func (m *RegisterUserReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "grpctest.RegisterUserRequest")
	proto.RegisterType((*RegisterUserRequest_SecurityQuestion)(nil), "grpctest.RegisterUserRequest.SecurityQuestion")
	proto.RegisterType((*RegisterUserReply)(nil), "grpctest.RegisterUserReply")
}

func init() { proto.RegisterFile("user_registration.proto", fileDescriptor_d02355805e6aa75f) }

var fileDescriptor_d02355805e6aa75f = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xfd, 0xc1, 0x4f, 0x08, 0x0e, 0x1c, 0x60, 0x35, 0xda, 0xd4, 0x18, 0x91, 0x13, 0xa7, 0x25,
	0xc1, 0xc4, 0x6f, 0xa0, 0x27, 0x63, 0x62, 0xd5, 0x93, 0x07, 0xdc, 0xc2, 0x58, 0x36, 0x69, 0xbb,
	0xeb, 0xec, 0x36, 0xa4, 0x9f, 0xd7, 0x2f, 0x62, 0xd8, 0x6d, 0xab, 0x12, 0x35, 0xf1, 0xf8, 0xde,
	0x9b, 0x3f, 0x6f, 0xde, 0xc0, 0x71, 0x61, 0x90, 0x16, 0x84, 0x89, 0x34, 0x96, 0x84, 0x95, 0x2a,
	0xe7, 0x9a, 0x94, 0x55, 0xac, 0x97, 0x90, 0x5e, 0x5a, 0x34, 0x36, 0x3c, 0x4b, 0x94, 0x4a, 0x52,
	0x9c, 0x39, 0x3e, 0x2e, 0x5e, 0x66, 0x56, 0x66, 0x68, 0xac, 0xc8, 0xb4, 0x2f, 0x9d, 0xbc, 0xb5,
	0xe1, 0x20, 0x72, 0x13, 0x90, 0x1e, 0x0d, 0x52, 0x84, 0xaf, 0x05, 0x1a, 0xcb, 0x0e, 0xa1, 0x83,
	0x99, 0x90, 0x69, 0xd0, 0x1a, 0xb7, 0xa6, 0xfb, 0x91, 0x07, 0x2c, 0x84, 0xde, 0x76, 0x67, 0x2e,
	0x32, 0x0c, 0xda, 0x4e, 0x68, 0xf0, 0x56, 0xd3, 0xc2, 0x98, 0x8d, 0xa2, 0x55, 0xf0, 0xdf, 0x6b,
	0x35, 0x66, 0x97, 0xd0, 0x8b, 0x25, 0xd9, 0xf5, 0x4a, 0x94, 0xc1, 0xde, 0xb8, 0x35, 0xed, 0xcf,
	0x43, 0xee, 0x9d, 0xf1, 0xda, 0x19, 0x7f, 0xa8, 0x9d, 0x45, 0x4d, 0x2d, 0x3b, 0x87, 0x81, 0x5e,
	0xab, 0x1c, 0x17, 0x79, 0x91, 0xc5, 0x48, 0x41, 0xc7, 0xcd, 0xed, 0x3b, 0xee, 0xd6, 0x51, 0xec,
	0x09, 0x46, 0x06, 0x97, 0x05, 0x49, 0x5b, 0x2e, 0x9c, 0x75, 0xa9, 0xf2, 0xa0, 0xeb, 0x76, 0x70,
	0x5e, 0xe7, 0xc0, 0xbf, 0x39, 0x91, 0xdf, 0x57, 0x6d, 0x77, 0x55, 0x57, 0x34, 0x34, 0x3b, 0x4c,
	0x78, 0x0d, 0xc3, 0xdd, 0xaa, 0xed, 0x9d, 0xcd, 0x1e, 0x1f, 0x4e, 0x83, 0xd9, 0x11, 0x74, 0x45,
	0x6e, 0x36, 0x48, 0x55, 0x3a, 0x15, 0x9a, 0x5c, 0xc1, 0xe8, 0xab, 0x03, 0x9d, 0x96, 0x7f, 0x8f,
	0x78, 0xfe, 0x0c, 0x43, 0xdf, 0xfe, 0xf1, 0x71, 0x76, 0x03, 0x83, 0xcf, 0xa3, 0xd9, 0xe9, 0xaf,
	0x47, 0x87, 0x27, 0x3f, 0xc9, 0x3a, 0x2d, 0x27, 0xff, 0xe2, 0xae, 0x7b, 0xc7, 0xc5, 0x7b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0xbe, 0xf4, 0x7b, 0x5b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserRegistrationClient is the client API for UserRegistration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserRegistrationClient interface {
	// Sends a greeting
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserReply, error)
}

type userRegistrationClient struct {
	cc *grpc.ClientConn
}

func NewUserRegistrationClient(cc *grpc.ClientConn) UserRegistrationClient {
	return &userRegistrationClient{cc}
}

func (c *userRegistrationClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserReply, error) {
	out := new(RegisterUserReply)
	err := c.cc.Invoke(ctx, "/grpctest.UserRegistration/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRegistrationServer is the server API for UserRegistration service.
type UserRegistrationServer interface {
	// Sends a greeting
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserReply, error)
}

func RegisterUserRegistrationServer(s *grpc.Server, srv UserRegistrationServer) {
	s.RegisterService(&_UserRegistration_serviceDesc, srv)
}

func _UserRegistration_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRegistrationServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctest.UserRegistration/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRegistrationServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRegistration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpctest.UserRegistration",
	HandlerType: (*UserRegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserRegistration_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_registration.proto",
}
